enum AppLanguage { it, en }

/// Stringhe statiche dell'interfaccia (italiano/inglese). I messaggi che
/// arrivano dal demone (es. errori di validazione del layout) restano in
/// italiano: tradurli richiederebbe localizzare anche daemon.py, fuori
/// scope per ora.
class Strings {
  const Strings(this.lang);

  final AppLanguage lang;

  bool get _it => lang == AppLanguage.it;

  // --- Impostazioni connessione ---
  String get connectionSettingsTitle =>
      _it ? 'Impostazioni connessione' : 'Connection settings';
  String get connectionIntro => _it
      ? 'Inserisci l\'indirizzo IP del PC dove gira Stenografa, la porta '
            '(di default 8765) e il token generato dal demone. Il token si '
            'trova in ~/.config/stenografa/config.json sul PC (mostrato '
            'anche in una notifica al primo avvio del demone aggiornato).'
      : 'Enter the IP address of the PC running Stenografa, the port '
            '(8765 by default) and the token generated by the daemon. The '
            'token is stored in ~/.config/stenografa/config.json on the PC '
            '(also shown in a notification the first time the updated '
            'daemon starts).';
  String get hostLabel => _it ? 'Indirizzo IP del PC' : 'PC IP address';
  String get portLabel => _it ? 'Porta' : 'Port';
  String get tokenLabel => _it ? 'Token (5 cifre)' : 'Token (5 digits)';
  String get testConnectionInProgress =>
      _it ? 'Verifica in corso…' : 'Testing…';
  String get testConnectionButton =>
      _it ? 'Verifica connessione' : 'Test connection';
  String get connectionSuccessful =>
      _it ? 'Connessione riuscita' : 'Connection successful';
  String get invalidToken => _it ? 'Token non valido' : 'Invalid token';
  String get connectionError =>
      _it ? 'Errore di connessione' : 'Connection error';
  String get connectionClosedNoReply => _it
      ? 'Connessione chiusa senza risposta'
      : 'Connection closed without a reply';
  String get connectionTimeout =>
      _it ? 'Timeout: PC non raggiungibile' : 'Timeout: PC unreachable';
  String connectionFailed(String error) =>
      _it ? 'Impossibile connettersi: $error' : 'Could not connect: $error';
  String get dictationLanguage =>
      _it ? 'Lingua di dettatura' : 'Dictation language';
  String get uiLanguage => _it ? 'Lingua interfaccia' : 'Interface language';
  String get restoreClipboardHelper => _it
      ? 'Dopo aver incollato il testo dettato, ripristina cio\' che avevi '
            'copiato prima di iniziare a dettare.'
      : 'After pasting the dictated text, restore whatever you had copied '
            'before you started dictating.';
  String get translateToggleTitle =>
      _it ? 'Traduci automaticamente' : 'Auto-translate';
  String get translateToggleHelper => _it
      ? 'Traduce il testo dettato con un pulsante microfono normale prima '
            'di incollarlo (non si applica ai pulsanti "Comando vocale IA").'
      : 'Translates the dictated text before pasting it, for a normal '
            'microphone button (does not apply to "Voice command AI" '
            'buttons).';
  String get translateTargetLabel =>
      _it ? 'Lingua di destinazione' : 'Target language';
  String get translateEngineLabel =>
      _it ? 'Motore di traduzione' : 'Translation engine';
  String get translateEngineWhisper => _it
      ? 'Whisper (solo inglese, veloce)'
      : 'Whisper (English only, fast)';
  String get translateEngineLlm => _it
      ? 'LM Studio (qualsiasi lingua)'
      : 'LM Studio (any language)';
  String get translateEngineNonEnglishNote => _it
      ? 'Per lingue diverse dall\'inglese si usa sempre LM Studio: Whisper '
            'puo\' tradurre solo verso l\'inglese.'
      : 'For languages other than English, LM Studio is always used: '
            'Whisper can only translate into English.';
  String get restartDaemonButton => _it ? 'Riavvia demone' : 'Restart daemon';
  String get restartDaemonConfirmTitle =>
      _it ? 'Riavviare il demone?' : 'Restart the daemon?';
  String get restartDaemonConfirmBody => _it
      ? 'La connessione si interrompe per qualche secondo, poi l\'app si '
            'riconnette da sola. Layout e impostazioni non vengono persi.'
      : 'The connection drops for a few seconds, then the app reconnects '
            'on its own. Layout and settings are not lost.';
  String get restartDaemonSent =>
      _it ? 'Riavvio inviato al demone' : 'Restart sent to the daemon';

  // --- azioni generiche ---
  String get save => _it ? 'Salva' : 'Save';
  String get cancel => _it ? 'Annulla' : 'Cancel';

  // --- Scelta fra piu' scorciatoie (comando vocale IA ambiguo) ---
  String get ambiguousCommandTitle =>
      _it ? 'Quale intendi?' : 'Which one do you mean?';
  String ambiguousCommandSubtitle(String text) =>
      _it ? 'Comando: "$text"' : 'Command: "$text"';
  String get create => _it ? 'Crea' : 'Create';
  String get remove => _it ? 'Rimuovi' : 'Remove';
  String get delete => _it ? 'Elimina' : 'Delete';
  String get close => _it ? 'Chiudi' : 'Close';
  String get settings => _it ? 'Impostazioni' : 'Settings';
  String get rename => _it ? 'Rinomina' : 'Rename';
  /// titolo dell'editor aperto con la pressione prolungata su un pulsante:
  /// da li' si cambiano nome, azione (combinazione/sequenza/testo), colore
  /// e icona
  String editButtonTitle(String label) =>
      _it ? 'Modifica "$label"' : 'Edit "$label"';
  /// editor del pulsante: quante celle occupa, per farne uno piu' grande
  String get sizeLabel => _it ? 'Dimensione (celle)' : 'Size (cells)';
  /// mostrato quando il pulsante e' circondato da vicini o dal bordo: senza
  /// una cella libera accanto non c'e' modo di ingrandirlo
  String get noRoomToGrow => _it
      ? 'Nessuna cella libera accanto: aggiungi una riga o una colonna con '
            'le barre ai bordi, oppure sposta prima i pulsanti vicini.'
      : 'No free cell next to it: add a row or a column with the bars at '
            'the edges, or move the neighbouring buttons first.';
  String get widthLabel => _it ? 'Larghezza' : 'Width';
  String get heightLabel => _it ? 'Altezza' : 'Height';
  String get moveLeft => _it ? 'Sposta a sinistra' : 'Move left';
  String get moveRight => _it ? 'Sposta a destra' : 'Move right';
  String get duplicate => _it ? 'Duplica' : 'Duplicate';

  // --- home: barra superiore / stati ---
  String get editModeOn => _it ? 'Fine modifica' : 'Done editing';
  String get editModeOff => _it ? 'Modifica scorciatoie' : 'Edit shortcuts';
  String get followActiveAppOn =>
      _it ? 'Segui app attiva: attivo' : 'Follow active app: on';
  String get followActiveAppOff =>
      _it ? 'Segui app attiva: disattivo' : 'Follow active app: off';
  String get newDashboard => _it ? 'Nuova dashboard' : 'New dashboard';
  String get removeRow => _it ? 'Rimuovi riga' : 'Remove row';
  String get addRow => _it ? 'Aggiungi riga' : 'Add row';
  String get removeColumn => _it ? 'Rimuovi colonna' : 'Remove column';
  String get addColumn => _it ? 'Aggiungi colonna' : 'Add column';
  String get rowsLabel => _it ? 'righe' : 'rows';
  String get colsLabel => _it ? 'colonne' : 'columns';

  // --- stato pulsante microfono ---
  String get recordingStopHint =>
      _it ? 'REC — tocca per fermare' : 'REC — tap to stop';
  String get transcribing => _it ? 'Trascrizione in corso…' : 'Transcribing…';
  String get loadingModel => _it ? 'Carico il modello…' : 'Loading model…';
  String get tapToRecord => _it ? 'Tocca per registrare' : 'Tap to record';
  /// spunta sul pulsante di registrazione: a incolla avvenuto il PC preme
  /// Invio, cosi' in chat il messaggio dettato parte da solo
  /// scritta accanto alla spunta, dentro il pulsante: deve stare in poco
  /// spazio e dire cosa succede a dettatura finita
  String get autoEnterLabel => _it ? 'Invio' : 'Send';
  String get autoEnterOn => _it
      ? 'Invio automatico attivo: il messaggio parte da solo'
      : 'Auto-send on: the message is sent by itself';
  String get autoEnterOff => _it
      ? 'Invio automatico spento: tocca per attivarlo'
      : 'Auto-send off: tap to turn it on';
  // --- controlli dei video in riproduzione sul PC ---
  String pauseMediaTooltip(String what) =>
      _it ? 'Metti in pausa: $what' : 'Pause: $what';
  String playMediaTooltip(String what) =>
      _it ? 'Riprendi: $what' : 'Resume: $what';
  String get pauseMediaWhileRecordingTitle => _it
      ? 'Metti in pausa i video mentre detto'
      : 'Pause videos while dictating';
  String get pauseMediaWhileRecordingHelper => _it
      ? 'All\'inizio della dettatura il PC mette in pausa i video in '
            'riproduzione e li fa ripartire alla fine, cosi\' il loro audio '
            'non finisce nella trascrizione. Quello che il browser non '
            'espone (piu\' schede che suonano insieme) viene silenziato '
            'invece che messo in pausa.'
      : 'When dictation starts, the PC pauses whatever is playing and '
            'resumes it at the end, so its audio does not end up in the '
            'transcription. Whatever the browser does not expose (several '
            'tabs playing at once) is muted instead of paused.';

  /// microfono disabilitato perche' la sessione in corso e' stata avviata
  /// da un altro pulsante microfono (es. registrazione avviata dal
  /// pulsante IA: il pulsante di registrazione resta spento)
  String get micBusyElsewhere =>
      _it ? 'Occupato da un altro pulsante' : 'Busy with another button';

  // --- pulsante "comando vocale IA" (kind="ai_command") ---
  String get tapForAiCommand =>
      _it ? 'Tocca e detta un comando' : 'Tap and dictate a command';
  // usato sia per l'interpretazione del comando vocale IA sia per
  // l'attesa della traduzione via LM Studio: stesso stato "thinking" del
  // demone in entrambi i casi
  String get aiThinking =>
      _it ? 'L\'IA sta elaborando…' : 'AI is processing…';
  String commandExecuted(String combo) =>
      _it ? 'Comando eseguito: $combo' : 'Command executed: $combo';


  // --- stato disconnesso ---
  String get connectingToPc =>
      _it ? 'Connessione al PC in corso…' : 'Connecting to PC…';
  String get invalidTokenCheckSettings => _it
      ? 'Token non valido\nControlla le impostazioni'
      : 'Invalid token\nCheck settings';
  String get notConnectedTapForSettings => _it
      ? 'Non connesso\nTocca lo schermo per le impostazioni'
      : 'Not connected\nTap the screen for settings';

  // --- dialoghi ---
  String get newButtonTitle => _it ? 'Nuovo pulsante' : 'New button';
  String get buttonTypeLabel => _it ? 'Tipo di pulsante' : 'Button type';
  String get shortcutOption => _it ? 'Scorciatoia' : 'Shortcut';
  String get microphoneOption => _it ? 'Microfono' : 'Microphone';
  String get aiCommandOption =>
      _it ? 'Comando vocale (IA)' : 'Voice command (AI)';
  String get labelField => _it ? 'Etichetta' : 'Label';
  String get keyComboField =>
      _it ? 'Combinazione di tasti' : 'Key combination';
  String get removeButtonTitle =>
      _it ? 'Rimuovere il pulsante?' : 'Remove this button?';
  String removeButtonBody(String description) => _it
      ? '$description verra\' rimosso dalla griglia.'
      : '$description will be removed from the grid.';
  String get microphoneParen => _it ? 'microfono' : 'microphone';
  String get nameField => _it ? 'Nome' : 'Name';
  String get dashboardSettingsTitle =>
      _it ? 'Impostazioni dashboard' : 'Dashboard settings';
  String get detectAppField =>
      _it ? 'Rileva app (opzionale)' : 'Detect app (optional)';
  String get detectAppHelper => _it
      ? 'Se il nome o il titolo della finestra col focus sul PC contiene '
            'questo testo, "Segui app attiva" mostrera\' questa dashboard. '
            'Per piu\' app separale con una virgola.'
      : 'If the name or title of the focused window on the PC contains '
            'this text, "Follow active app" will show this dashboard. For '
            'more than one app, separate them with a comma.';
  String appearanceOf(String label) =>
      _it ? 'Aspetto di "$label"' : 'Appearance of "$label"';
  String get colorLabel => _it ? 'Colore' : 'Color';
  String get iconLabel => _it ? 'Icona' : 'Icon';
  String get pastedOnPc => _it ? 'Incollato sul PC' : 'Pasted on the PC';
  String get copiedManualPaste =>
      _it ? 'Copiato (incolla manualmente)' : 'Copied (paste manually)';
  String get duplicateDashboardTitle =>
      _it ? 'Duplica dashboard' : 'Duplicate dashboard';
  String duplicateDashboardHint(String name) => _it
      ? '$name (copia)'
      : '$name (copy)';

  // --- nuovi tipi di pulsante ---
  String get macroOption => _it ? 'Macro (sequenza)' : 'Macro (sequence)';
  String get textOption => _it ? 'Testo da incollare' : 'Text to paste';
  String get launchOption => _it ? 'Avvia applicazione' : 'Launch application';
  // --- pulsante "re-incolla l'ultima dettatura" (kind="paste_last") ---
  String get pasteLastOption =>
      _it ? 'Incolla ultima dettatura' : 'Paste last dictation';
  String get pasteLastDefaultLabel => _it ? 'Incolla ultimo' : 'Paste last';
  String get pasteLastHelper => _it
      ? 'Re-incolla l\'ultimo testo dettato, senza registrarlo di nuovo: '
            'utile se il cursore non era dove volevi.'
      : 'Pastes the last dictated text again, with no new recording: '
            'handy when the cursor was not where you wanted it.';
  String get macroCombosField => _it
      ? 'Combinazioni, una per riga'
      : 'Key combinations, one per line';
  String get macroCombosHelper => _it
      ? 'Vengono eseguite in ordine. Se una fallisce la sequenza si ferma.'
      : 'They run in order. If one fails the sequence stops.';
  String get macroDelayField =>
      _it ? 'Pausa fra i passi (ms)' : 'Delay between steps (ms)';
  String get textToPasteField => _it ? 'Testo' : 'Text';
  String get chooseAppLabel =>
      _it ? 'Applicazione da avviare' : 'Application to launch';
  String get loadingApps => _it ? 'Carico le app…' : 'Loading apps…';
  String get noAppsFound =>
      _it ? 'Nessuna applicazione trovata' : 'No applications found';
  String get searchAppHint => _it ? 'Cerca…' : 'Search…';
  String appLaunched(String name) =>
      _it ? 'Avviata: $name' : 'Launched: $name';

  // --- storico dettature ---
  String get historyTitle => _it ? 'Ultime dettature' : 'Recent dictations';
  String get historyTooltip => _it ? 'Storico dettature' : 'Dictation history';
  String get historyEmpty => _it
      ? 'Nessuna dettatura in questa sessione.\nLo storico vive solo in '
            'memoria sul PC e si azzera al riavvio del demone.'
      : 'No dictation in this session.\nThe history lives only in memory on '
            'the PC and is cleared when the daemon restarts.';
  String get historyPasteAgain => _it ? 'Incolla di nuovo' : 'Paste again';
  String get historyNotPasted =>
      _it ? 'incolla non riuscito' : 'paste failed';
  String get historyPasteSent =>
      _it ? 'Re-incolla inviato al PC' : 'Re-paste sent to the PC';

  // --- conferma prima dell'incolla ---
  String get confirmPasteTitle =>
      _it ? 'Incollare questo testo?' : 'Paste this text?';
  String get confirmPasteHelper => _it
      ? 'Puoi correggerlo prima di incollarlo sul PC.'
      : 'You can fix it before pasting it on the PC.';
  String get confirmPasteButton => _it ? 'Incolla' : 'Paste';
  String get confirmBeforePasteTitle =>
      _it ? 'Conferma prima di incollare' : 'Confirm before pasting';
  String get confirmBeforePasteHelper => _it
      ? 'Invece di incollare subito, il testo dettato compare qui per essere '
            'riletto o corretto. Comodo per le dettature lunghe, di troppo '
            'per quelle rapide.'
      : 'Instead of pasting right away, the dictated text shows up here to '
            'be reviewed or fixed. Handy for long dictations, in the way for '
            'quick ones.';

  // --- vocabolario di dettatura ---
  String get vocabularyTitle => _it ? 'Vocabolario' : 'Vocabulary';
  String get vocabularyHelper => _it
      ? 'Termini che Whisper sbaglia sistematicamente (nomi propri, gergo '
            'tecnico), separati da virgola. Mettici solo quelli che vengono '
            'davvero sbagliati: liste lunghe peggiorano la trascrizione.'
      : 'Terms Whisper keeps getting wrong (proper nouns, jargon), separated '
            'by commas. Only add the ones that actually come out wrong: long '
            'lists make transcription worse.';
  String get dashboardVocabularyField => _it
      ? 'Vocabolario dettatura (opzionale)'
      : 'Dictation vocabulary (optional)';
  String get dashboardVocabularyHelper => _it
      ? 'Termini specifici di questa app, usati quando detti da un pulsante '
            'di questa dashboard.'
      : 'Terms specific to this app, used when you dictate from a button of '
            'this dashboard.';

  // --- push-to-talk e feedback ---
  String get pushToTalkTitle => _it ? 'Tieni premuto per parlare' : 'Push to talk';
  String get pushToTalkHelper => _it
      ? 'I pulsanti microfono registrano finche\' li tieni premuti, invece '
            'di funzionare da interruttore. Evita le registrazioni lasciate '
            'aperte per sbaglio.'
      : 'Microphone buttons record while you hold them, instead of acting as '
            'a toggle. Avoids recordings accidentally left running.';
  String get hapticsTitle => _it ? 'Vibrazione' : 'Vibration';
  String get hapticsHelper => _it
      ? 'Vibra all\'inizio e alla fine della registrazione e sull\'esito: il '
            'riscontro scritto arriva sul PC, cioe\' dove non stai '
            'guardando.'
      : 'Vibrates when recording starts and ends and on the outcome: the '
            'written feedback shows up on the PC, which is not where you are '
            'looking.';
  String get pushToTalkHint =>
      _it ? 'Tieni premuto per registrare' : 'Hold to record';

  // --- chiusura automatica sul silenzio ---
  String get silenceTimeoutTitle =>
      _it ? 'Chiudi da sola dopo il silenzio' : 'Stop by itself after silence';
  String get silenceTimeoutHelper => _it
      ? 'Passati questi secondi senza sentirti parlare, la dettatura si chiude '
            'da sola e incolla quello che ha raccolto. Comodo con '
            'l\'attivazione vocale, quando ci si dimentica la frase di stop. '
            'Non vale per "tieni premuto per parlare", dove è il dito a '
            'chiudere.'
      : 'After these seconds without hearing you speak, dictation stops by '
            'itself and pastes what it collected. Handy with voice activation, '
            'when you forget the stop phrase. Does not apply to push to talk, '
            'where releasing your finger ends it.';
  String get silenceTimeoutOff => _it ? 'Mai' : 'Never';
  String silenceTimeoutSeconds(int seconds) =>
      _it ? 'Dopo $seconds secondi' : 'After $seconds seconds';

  // --- attivazione vocale ---
  String get wakeWordTitle => _it ? 'Attivazione vocale' : 'Voice activation';
  String get wakeWordIntro => _it
      ? 'Avvia e ferma la dettatura pronunciando una frase, senza toccare il '
            'pulsante. Le frasi valgono per entrambi gli ascolti qui sotto.'
      : 'Start and stop dictation by saying a phrase, without touching the '
            'button. The phrases apply to both listeners below.';
  String get wakeWordOnPc => _it ? 'Ascolta dal PC' : 'Listen on the PC';
  String get wakeWordOnPcHelper => _it
      ? 'Il PC tiene aperto il microfono e aspetta la frase. E\' l\'opzione '
            'piu\' comoda: funziona anche a telefono spento o in tasca.'
      : 'The PC keeps the microphone open waiting for the phrase. The handiest '
            'option: it works with the phone off or in your pocket.';
  String get wakeWordOnPhone =>
      _it ? 'Ascolta dal telefono' : 'Listen on the phone';
  String get wakeWordOnPhoneHelper => _it
      ? 'Il telefono ascolta col proprio microfono, mentre l\'app e\' aperta. '
            'Utile se sei lontano dal PC. Consuma batteria.'
      : 'The phone listens with its own microphone while the app is open. '
            'Useful when you are away from the PC. Uses battery.';
  String get wakeWordPhoneUnavailable => _it
      ? 'Il telefono non puo\' ascoltare: manca il permesso del microfono o il '
            'riconoscimento vocale non e\' disponibile.'
      : 'The phone cannot listen: the microphone permission is missing or '
            'speech recognition is unavailable.';
  String get wakeWordListeningNow => _it ? 'In ascolto' : 'Listening';
  String get wakePhraseStartLabel => _it ? 'Frase di avvio' : 'Start phrase';
  String get wakePhraseStopLabel => _it ? 'Frase di stop' : 'Stop phrase';
  String get wakePhraseHelper => _it
      ? 'Scegli parole che non diresti per caso parlando: un nome inventato '
            'funziona meglio di una parola comune. Se finiscono nel testo '
            'dettato, il PC le toglie da solo. Puoi elencare piu\' forme '
            'separate da virgola (es. "jarvis, già visto"): serve quando il '
            'telefono capisce la tua frase in un altro modo.'
      : 'Pick words you would not say by accident: a made-up name works better '
            'than a common word. If they end up in the dictated text, the PC '
            'removes them for you. You can list several forms separated by '
            'commas (e.g. "jarvis, already seen"): useful when the phone hears '
            'your phrase differently.';
  String get wakeHeardTitle =>
      _it ? 'Ultima frase sentita' : 'Last phrase heard';
  String get wakeHeardHelper => _it
      ? 'Quello che il riconoscimento vocale ha capito. Se la tua frase compare '
            'qui scritta diversamente, aggiungila sopra separata da virgola: '
            'da quel momento verra\' riconosciuta.'
      : 'What speech recognition understood. If your phrase shows up here '
            'spelled differently, add it above separated by a comma: from then '
            'on it will be recognised.';
  String get wakeSilenceBeepsTitle => _it
      ? 'Silenzia i segnali acustici'
      : 'Silence the beeps';
  String get wakeSilenceBeepsHelper => _it
      ? 'Android fa suonare un segnale ad ogni sessione di ascolto, non ad ogni '
            'dettatura: senza questo il telefono trilla di continuo anche '
            'stando zitti. Restano udibili mentre detti. Silenzia anche '
            'l\'audio del telefono durante l\'attesa.'
      : 'Android beeps on every listening session, not on every dictation: '
            'without this the phone keeps chirping even in silence. Beeps stay '
            'audible while you dictate. It also mutes the phone\'s audio while '
            'waiting.';
  String get wakeHeardFromPc => _it ? 'Dal PC' : 'From the PC';
  String get wakeHeardFromPhone => _it ? 'Dal telefono' : 'From the phone';
  String get wakeHeardNothingYet =>
      _it ? 'Ancora niente' : 'Nothing yet';
  String get wakePhraseTooShort => _it
      ? 'Troppo corta: servono almeno 3 lettere.'
      : 'Too short: at least 3 letters are needed.';
  String get wakePhrasesMustDiffer => _it
      ? 'Le due frasi devono essere diverse.'
      : 'The two phrases must be different.';

  // --- sicurezza del collegamento ---
  String get securityTitle => _it ? 'Sicurezza' : 'Security';
  String get connectionEncrypted =>
      _it ? 'Collegamento cifrato' : 'Encrypted connection';
  String get connectionPlain =>
      _it ? 'Collegamento in chiaro' : 'Unencrypted connection';
  String get connectionPlainHelper => _it
      ? 'Sulla stessa rete WiFi, chiunque puo\' leggere quello che detti e '
            'il token. Aggiorna il demone sul PC (serve openssl) per '
            'cifrarlo.'
      : 'On the same WiFi, anyone can read what you dictate and the token. '
            'Update the daemon on the PC (openssl required) to encrypt it.';
  String certificateFingerprint(String fingerprint) =>
      _it ? 'Certificato: $fingerprint' : 'Certificate: $fingerprint';
  String get requireTlsTitle =>
      _it ? 'Richiedi collegamento cifrato' : 'Require encrypted connection';
  String get requireTlsHelper => _it
      ? 'Il PC rifiuta i collegamenti in chiaro. Attivalo quando tutti i '
            'telefoni che usi sono aggiornati.'
      : 'The PC refuses unencrypted connections. Turn it on once every phone '
            'you use is updated.';
  String get certificateChangedTitle =>
      _it ? 'Il certificato del PC e\' cambiato' : 'The PC certificate changed';
  String certificateChangedBody(String presented) => _it
      ? 'Il PC si presenta con un certificato diverso da quello accettato la '
            'prima volta:\n\n$presented\n\nE\' normale se hai reinstallato o '
            'ripristinato il demone. Se non hai fatto nulla del genere, '
            'qualcuno sulla rete potrebbe spacciarsi per il tuo PC: '
            'confronta l\'impronta con quella mostrata dal demone prima di '
            'accettare.'
      : 'The PC is presenting a certificate different from the one accepted '
            'the first time:\n\n$presented\n\nThat is expected if you '
            'reinstalled or restored the daemon. If you did nothing of the '
            'sort, someone on the network may be impersonating your PC: '
            'compare the fingerprint with the one shown by the daemon before '
            'accepting.';
  String get certificateAcceptButton =>
      _it ? 'Accetta il nuovo certificato' : 'Accept the new certificate';
}
